version: '3.0'

services:

  quarkusapp:
    build: .
    image: quarkusapp:latest
    container_name: quarkusapp
    hostname: quarkusapp
    depends_on:
      - collector
    ports:
      - "8080:8080"
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:5555
      - OTEL_TRACES_SAMPLER=always_on
      - OTEL_IMR_EXPORT_INTERVAL=5000
      - OTEL_METRIC_EXPORT_INTERVAL=5000
      - OTEL_RESOURCE_ATTRIBUTES=service.name=quarkusapp,service.version=1.0,deployment.environment=production

  collector:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    container_name: collector
    hostname: collector
    command: [ "--config=/etc/collector-config.yaml" ]
    environment:
      - AWS_PROFILE=default
    volumes:
      - ./collector-config-aws.yaml:/etc/collector-config.yaml
      - ~/.aws:/root/.aws
    ports:
      - "5555:5555"

networks:
  default:
    name: inst-java-apps-using-otel
